### ISSUE TITLE
Zeebe's new Clock mechanism should be supported in ZPT

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe-process-test#1225]
## Description

Currently the CI fails becasue no clock source has been specified:

```
java.lang.NullPointerException: Must specify a clock source
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at io.camunda.zeebe.logstreams.impl.log.LogStreamBuilderImpl.validate(LogStreamBuilderImpl.java:90)
	at io.camunda.zeebe.logstreams.impl.log.LogStreamBuilderImpl.build(LogStreamBuilderImpl.java:81)
	at io.camunda.zeebe.process.test.engine.EngineFactory.createLogStream(EngineFactory.java:129)
	at io.camunda.zeebe.process.test.engine.EngineFactory.create(EngineFactory.java:68)
	at io.camunda.zeebe.process.test.engine.EngineFactory.create(EngineFactory.java:57)
	at io.camunda.zeebe.process.test.engine.EngineFactory.create(EngineFactory.java:39)
	at io.camunda.zeebe.process.test.engine.EngineClientTest.setupGrpcServer(EngineClientTest.java:77)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.process.test.api.ZeebeTestEngine.stop()" because "this.zeebeEngine" is null
		at io.camunda.zeebe.process.test.engine.EngineClientTest.tearDown(EngineClientTest.java:84)
		... 3 more
```

I've tried adding the clock source with `InstantSource.system()`. However, once I do that any tests that rely on increasing the engine time are failing. I don't know all the details about the new clock and how it works myself.

**Comment by lenaschoenburg** [comment]
Try using `ActorClock.current()` or whatever `ControllableActorClock` you have available. The tests rely on modifying the actor clock, using `InstantSource.system()` circumvents that.
