### ISSUE TITLE
Improve error message when engine is not started

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe-process-test#339]
**Description**

If the engine within the testcontainer is not started and we try to communicate with it we get the following exception:
```
2022-04-25 10:20:03.631  WARN 6632 --- [ault-executor-0] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker test1 and job type test1

io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
        at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.45.1.jar:1.45.1]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[grpc-stub-1.45.1.jar:1.45.1]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562) ~[grpc-core-1.45.1.jar:1.45.1]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.45.1.jar:1.45.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743) ~[grpc-core-1.45.1.jar:1.45.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722) ~[grpc-core-1.45.1.jar:1.45.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.45.1.jar:1.45.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.45.1.jar:1.45.1]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
Instead of this unknown exception we should mention that the engine is currently not running and that the `start()` method should be called first.

**Comment by saig0** [comment]
> [!Note]
> Heads up! We are building a new Java testing library for Camunda 8.6. The new library will replace Zeebe Process Test.
> Read more about upcoming changes [here](https://github.com/camunda/issues/issues/751) and stay tuned for updates. :rocket:

**Comment by saig0** [comment]
Closing as out of scope for maintenance mode. We will not work on features or non-critical changes.
