### ISSUE TITLE
Make the hasPassed() assertion more informative

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/zeebe-process-test#369]
**Description**

running this assertion:
```
    assertThat(processInstanceEvent)
      .hasPassedElement("StartEvent_");
```
throws an assertion error like

```
java.lang.AssertionError: Expected element with id StartEvent_ to be passed 1 times, but was 0
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.hasPassedElement(ProcessInstanceAssert.java:226)
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.hasPassedElement(ProcessInstanceAssert.java:189)
	at com.camunda.consulting.ExampleProcessUnitTest.testHappyPath(ExampleProcessUnitTest.java:35)
...
```

A message like 
```
Could not find StartEvent_ in the list of passed elements. Instead the process has passed [StartEvent_1, Activity_2]
```
is more helpful.

camunda-bpm-assert shows this error message: https://github.com/camunda/camunda-bpm-platform/blob/master/test-utils/assert/core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessInstanceAssert.java#L287

**Comment by manish-singh-bisht** [comment]
Hi @ingorichtsmeier correct me if I am wrong ,you are asking to change the error message to the following message you provided?
If so, I would love to work on it.

**Comment by saig0** [comment]
> [!Note]
> Heads up! We are building a new Java testing library for Camunda 8.6. The new library will replace Zeebe Process Test.
> Read more about upcoming changes [here](https://github.com/camunda/issues/issues/751) and stay tuned for updates. :rocket:

**Comment by saig0** [comment]
Closing as out of scope for maintenance mode. We will not work on features or non-critical changes.
