### ISSUE TITLE
PullRequestProcessTest.testRemindReviewer is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe-process-test#984]
The test is failing with:

```
Error:  io.camunda.zeebe.process.test.examples.PullRequestProcessTest.testRemindReviewer -- Time elapsed: 4.264 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unable to activate 1 jobs, because only 0 were activated.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.completeServiceTasks(PullRequestProcessTest.java:280)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.completeServiceTask(PullRequestProcessTest.java:269)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.testRemindReviewer(PullRequestProcessTest.java:136)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
	

[More logs here](https://github.com/camunda/zeebe-process-test/files/13392306/Unit.Test.Results.ubuntu-latest.zip)

**Comment by ana-vinogradova-camunda** [comment]
Just happened to me:
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.016 s <<< FAILURE! -- in io.camunda.zeebe.process.test.examples.PullRequestProcessTest
[zb-actors-0] INFO io.camunda.zeebe.logstreams.impl.log.Sequencer - Closing sequencer for writing
Error:  io.camunda.zeebe.process.test.examples.PullRequestProcessTest.testRemindReviewer -- Time elapsed: 6.121 s <<< FAILURE!
[zb-actors-0] INFO io.camunda.zeebe.logstreams - On closing logstream null close 2 readers
org.opentest4j.AssertionFailedError: Unable to activate 1 jobs, because only 0 were activated.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.completeServiceTasks(PullRequestProcessTest.java:280)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.completeServiceTask(PullRequestProcessTest.java:269)
	at io.camunda.zeebe.process.test.examples.PullRequestProcessTest.testRemindReviewer(PullRequestProcessTest.java:136)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

[Build here](https://github.com/camunda/zeebe-process-test/actions/runs/7541061338/job/20528255529?pr=1028)

**Comment by koevskinikola** [comment]
Happened again: https://github.com/camunda/zeebe-process-test/actions/runs/7564734652/job/20599341063
